name: bjornt-prometheus-haproxy-exporter
version: 0.7.1
summary: Prometheus HAProxy Exporter
description: |
  Exporter that exposes information gathered from HAProxy.
confinement: strict
apps:
  node-exporter:
    command: 'bin/haproxy_exporter -haproxy.scrape-uri="http://haproxy:haproxy@localhost:10000/\;csv"'
    plugs: [network-bind, network]
    daemon: simple
parts:
  node-exporter:
    plugin: go
    go-importpath: github.com/prometheus/haproxy_exporter
    source: .
